template: |
  ## What’s Changed

  $CHANGES

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  default: minor

name-template: "$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
